# TTSmate V1 配置文件示例
# 复制此文件为 config.toml 并根据需要修改配置

[tts]
# TTS服务器配置
server_url = "http://192.168.11.153:8080"
timeout_seconds = 30
retry_count = 3
cache_enabled = true
default_voice = "Default"
audio_format = "wav"

[ai]
# AI文案生成配置
api_key = ""  # 请填入您的DeepSeek API密钥
base_url = "https://api.deepseek.com"
model = "deepseek-chat"
max_tokens = 1000
temperature = 0.7
timeout_seconds = 30

[audio]
# 音频配置
sample_rate = 44100
buffer_size = 1024
channels = 2
bit_depth = 16
master_volume = 1.0
enable_virtual_cable = true
enable_voicemeeter = false

[ui]
# 用户界面配置
theme = "dark"
font_size = 14.0
window_width = 1200.0
window_height = 800.0
auto_save = true
show_tooltips = true

[keybindings]
# 快捷键配置
tts_generate = "F1"
ai_generate = "F2"
stop_all = "Escape"
volume_up = "Ctrl+Up"
volume_down = "Ctrl+Down"
