# TTSmate V1 配置文件示例
# 复制此文件为 config.toml 并根据需要修改配置

[tts]
# TTS配置
timeout_seconds = 30
retry_count = 3
cache_enabled = true
default_voice = "1"  # 默认使用标准女声
audio_format = "mp3"

[tts.baidu]
# 百度TTS API配置
api_key = "F9R262dgN5LcXOtNTRcQ6u1u"  # 百度API密钥
secret_key = "uRHLKBxb9ggQqxHlwSMrio8UTC5hhmNT"  # 百度Secret Key
cuid = "TTSmate"  # 用户唯一标识
speed = 5  # 语速，取值0-15，默认为5中语速
pitch = 5  # 音调，取值0-15，默认为5中语调
volume = 5  # 音量，取值0-15，默认为5中音量
voice = 1  # 发音人选择，默认为1
aue = 3  # 音频格式：3=mp3(默认)；4=pcm-16k；5=pcm-8k；6=wav

[ai]
# AI文案生成配置
api_key = ""  # 请填入您的DeepSeek API密钥
base_url = "https://api.deepseek.com"
model = "deepseek-chat"
max_tokens = 1000
temperature = 0.7
timeout_seconds = 30

[audio]
# 音频配置
sample_rate = 44100
buffer_size = 1024
channels = 2
bit_depth = 16
master_volume = 1.0
enable_virtual_cable = true
enable_voicemeeter = false

[ui]
# UI配置
theme = "dark"
font_size = 14.0
window_width = 1200.0
window_height = 800.0
auto_save = true
show_tooltips = true

[keybindings]
# 快捷键配置
tts_generate = "F1"
ai_generate = "F2"
stop_all = "Escape"
volume_up = "Ctrl+Up"
volume_down = "Ctrl+Down"
